services:
  mongo:
    image: mongo:7
    container_name: weather-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  weather-grpc:
    build:
      context: .
      dockerfile: Docker.weather
    container_name: weather-grpc
    env_file: .env
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    ports:
      - "50052:50052"
    depends_on:
      - mongo

volumes:
  mongo_data:
